### ISSUE TITLE
Error: Invalid value for <path> attribute d="MNaN,NaNA150.1,150.1 0 1..."

### ISSUE THREAD

**Issue by oren** [hij1nx/prohub#9]
I don't see any graphs on /project/:project-id
I see an error in the chrome console: 
```
Error: Invalid value for <path> attribute d="MNaN,NaNA150.1,150.1 0 1,1 NaN,NaNLNaN,NaNA90.05999999999999,90.05999999999999 0 1,0 NaN,NaNZ"
```

I added the -d to browserify to enable source map support:
`./node_modules/.bin/browserify -t jadeify -d ./app/client.js > ./app/assets/js/index.js`
and that's where the error is coming from: d3.js, line 8469: this.setAttribute(name, f(t));

Also, it might be an issue with the way I am adding projects. I just enter one of my project's names but there is no validation there so it let me add anything I type in the textbox. 
you can see my site running here: http://76.171.205.20:5000

I also had to remove this line  `+ '&redirect_uri=' + redirectURI` from node_modules/github-oauth/index.js to make the oauth works but that might be an issue with github-oauth and using a port that is not 80.

**Comment by hij1nx** [comment]
Fixed. When there were no projects it was trying to render the d3 chart.

**Comment by hij1nx** [comment]
> I also had to remove this line + '&redirect_uri=' + redirectURI from node_modules/github-oauth/index.js to make the oauth works but that might be an issue with github-oauth and using a port that is not 80.

Hmm, not sure about this. This seems fine for me and im not using port 80, can you describe the steps to reproduce a little more?

**Comment by oren** [comment]
are you running the project on a host with a real domain name? i am running it on my server and using whatever IP i get from my ISP. not sure if that's related.

**Comment by hij1nx** [comment]
I just have it running on `0.0.0.0:8080`, but I do know of someone who put it on docker and ran it under an actual domain. I totally appreciate your interest and would love to help you :) Can you pull the latest code and try to provide as much detail as possible about your configuration?

**Comment by oren** [comment]
sure. i'll have to wait for the weekend if that's ok.

**Comment by hij1nx** [comment]
:+1: :)
